Repository davidverweij/csv2docx, pull requests merged in 2020-05, with the labels that each got.

#4 Upgrade to Python 3.8 (from 2.7)
  .gitignore
  README.md
  docx-csv-mailmerge.py
  example.docx
  poetry.lock
  pyproject.toml
Labels: enhancement, refactoring

#24 Create pull request template
  .github/pull_request_template.md
Labels: documentation

#28 Unittests, linting and code formatting using nox
  .flake8
  .github/pull_request_template.md
  .pre-commit-config.yaml
  README.md
  csv2docx/cli.py
  noxfile.py
  poetry.lock
  pyproject.toml
  src/csv2docx/__init__.py
  src/csv2docx/cli.py
  src/csv2docx/csv2docx.py
  tests/__init__.py
  tests/data/example_missing_column.csv
  tests/test_cli.py
Labels: enhancement

#29 Type hinting with static type analysis
  .pre-commit-config.yaml
  README.md
  mypy.ini
  noxfile.py
  poetry.lock
  pyproject.toml
  src/csv2docx/cli.py
  src/csv2docx/csv2docx.py
  tests/test_cli.py
Labels: enhancement

#31 Updated README - fix python example
  README.md
  images/1_add_field.png
  images/2_toggle_field.png
  images/prep_docx.png
  pyproject.toml
Labels: documentation
